# 本文件是 TkTTS 的一部分
# SPDX-FileCopyrightText: 2025 thiliapr <thiliapr@tutanota.com>
# SPDX-FileContributor: thiliapr <thiliapr@tutanota.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

# 预处理
AUDIO_SUFFIXES = [".flac", ".wav", ".ogg", ".mp3"]
DEFAULT_SAMPLE_RATE = 24000
DEFAULT_FFT_LENGTH = 1024
DEFAULT_WIN_LENGTH = DEFAULT_FFT_LENGTH
DEFAULT_HOP_LENGTH = 256
DEFAULT_FRAME_LENGTH = 2 * DEFAULT_WIN_LENGTH
DEFAULT_NUM_MELS = 80

# 模型配置
DEFAULT_NUM_HEADS = 8
DEFAULT_DIM_HEAD = 64
DEFAULT_DIM_FEEDFORWARD = DEFAULT_NUM_HEADS * DEFAULT_DIM_HEAD * 4
DEFAULT_FFT_CONV1_KERNEL_SIZE = 9
DEFAULT_FFT_CONV2_KERNEL_SIZE = 1
DEFAULT_PREDICTOR_KERNEL_SIZE = 3
DEFAULT_VARIANCE_BINS = 256
DEFAULT_NUM_ENCODER_LAYERS = 4
DEFAULT_NUM_DECODER_LAYERS = 6

# 训练超参
DEFAULT_LEARNING_RATE = 5e-5  # 学习率
DEFAULT_WEIGHT_DECAY = 1e-2  # 权重衰减（L2正则化）系数
DEFAULT_DROPOUT = 0.1  # Dropout 概率
